#'Mixture-amount experiment
#'
#'A pharmaceutical mixture-amount experiment in two components
#'
#'@format A data frame with 360 observations on the following 3 variables.
#'\describe{
#' \item{Component_1}{Component 1 amount (mg)}
#' \item{Component_2}{Component 2 amount (mg)}
#' \item{Percent}{Percent of cells killed (response)}
#'}
#'@examples
#'plot(Drug[,1:2])
"Drug"
#' A simulated dataset based on a quadratic function
#' 
#' The dataset is simulated from the following function 
#' \insertCite{BoxDraper}{OptimaRegion}:
#' \deqn{
#' f(x) =  57.31 + 1.5 x_1 - 2.13 x_2 + 1.81 x_3
#' - 7.13 x_1 x_2 - 3.27 x_1 x_3 - 2.73 x_2 x_3 - 4.69 x_1^2 - 6.27 x_2^2 - 5.21 x_3^2,
#' }
#' defined in the region R = \{-2 <= x_i <= 2, for i = 1, 2, 3\}, with its maximum at 
#' (0.46, -0.46, 0.15).
#' The sample locations are generated via a Hyper Latin Square (HLS) design within R,
#' and the noisy level is sigma = 10. 
#' 
#' @format A list consisting of 2 components:
#' \describe{
#'   \item{design_matrix}{200 design points generated by a HLS design within R}
#'   \item{responses}{200 noisy responses simulated at the design points (sigma = 10)}
#' }
#' 
#' @references{
#'   \insertAllCited{}
#' }
#' @importFrom Rdpack reprompt
"quad_3D"
#' A simulated dataset based on a cubic function
#' 
#' The dataset is simulated from the following function 
#' \deqn{
#' f(x) =  10 - (x_1-1.5)^2 - (x_2-2)^2 - (x_3-2.5)^2 - (x_4-3)^2- (x_5-3.5)^2 
#' + 0.1 x_1^3 - 0.1 x_2^3 - 0.1 x_3^3 - 0.1 x_4^3 - 0.1 x_5^3 + x_2 x_4 - x_3 x_4
#' }
#' defined in the region R = \{ 0 <= x_i <= 5, for i = 1, ...,  5\}, with its maximum at 
#' (2.28, 2.44, 1.02, 2.65, 2.54).
#' The sample locations are generated via a Hyper Latin Square (HLS) design within R,
#' and the noisy level is sigma = 6. 
#' 
#' @format A list consisting of 2 components:
#' \describe{
#'   \item{design_matrix}{300 design points generated by a HLS design within R}
#'   \item{responses}{4500 noisy responses simulated at the design points with 
#'                    replicate = 15 and sigma = 6}
#' }
"cubic_5D"

